---
# YAML documents begin with the document separator ---
 
# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-
 
  # Hosts: where our play will run and options it will run with
  hosts: linux

  # Tasks: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:

    - name: Make Facts directory
      file:
        path: /home/ansible/facts.d
        recurse: yes
        state: directory
        owner: ansible

    - name: Copy fact 1
      copy:
        src: facts.d/getdate1.fact
        dest:  /etc/ansible/facts.d/getdate1.fact
        mode: 0755

    - name: Copy fact 2
      copy:
        src: facts.d/getdate2.fact
        dest:  /etc/ansible/facts.d/getdate2.fact
        mode: 0755

    - name: Refresh Facts
      setup:
        fact_path: /home/ansible/facts.d

    - name: Show IP adress
      debug:
        msg: "{{ ansible_default_ipv4.address }}"

# Three dots indicate the end of a YAML document
...
