---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
- hosts: all
  vars_prompt:

    - name: username
      prompt: What is your username?
      private: no

    - name: password
      prompt: What is your surname?
      private: no
  tasks:

    - name: Print a message
      debug:
        msg: " your name and surename: {{ username, password }}"
